import type { AgentTrace, VoiceExample } from '../app/core/content/demo-artifacts';

// Imported by unit tests and the isolated local preview only. Never production evidence.
const review = {
  origin: 'fixture' as const,
  version: 'mechanical-test-v1',
  recordedOn: '2026-09-08',
  provenance: 'Materiał techniczny przygotowany wyłącznie do testów komponentu.',
  limitations: 'Nie przedstawia rozmowy, klienta, integracji ani wykonania modelu AI.',
  reviewReference: null,
  privacyReviewed: false,
};

export const voiceFixture: VoiceExample = {
  review,
  title: 'Test odtwarzacza — sekunda ciszy',
  audioPath: '/assets/demo-evidence/player-silence.wav',
  audioSha256: '56d4af65701c26df20bd4021eda95b6e830348ce3a746086079fe89285548dc9',
  durationSeconds: 1,
  rightsReference: null,
  playbackVerified: false,
  extractionVerified: false,
  editingNote: 'Plik PCM wygenerowany z zerowych próbek. Nie zawiera głosu ani rozmowy.',
  transcript: [
    {
      id: 'silence',
      startSeconds: 0,
      endSeconds: 1,
      speaker: 'Opis pliku testowego',
      text: 'Jedna sekunda ciszy. Ten tekst opisuje zawartość pliku; nie jest transkrypcją wypowiedzi.',
    },
  ],
  result: [
    {
      label: 'Zawartość testowa',
      value: 'Cisza, bez wypowiedzi i bez ekstrakcji danych.',
      segmentId: 'silence',
    },
  ],
  handoff: null,
};

export const traceFixture: AgentTrace = {
  review,
  task: 'Test widoku zależnych kroków',
  whyAi: 'To wyłącznie fixture interfejsu. Nie wykonano modelu ani oceny, czy AI jest potrzebne.',
  result: 'Przygotowano dane testowe widoku. Nie uruchomiono agenta ani zapisu w systemie.',
  state: 'succeeded',
  executionReference: 'fixture-only-no-execution',
  timingSource: 'Ręcznie zadane znaczniki czasu fixture; to nie jest pomiar.',
  cost: null,
  steps: [
    {
      id: 'read',
      title: 'Odczyt danych testowych',
      kind: 'tool',
      state: 'succeeded',
      dependsOn: [],
      startedMs: 0,
      endedMs: 1,
      summary: 'Opis kroku do sprawdzenia listy; narzędzie nie zostało wywołane.',
      changesExternalState: false,
      approvalStepId: null,
      actorReference: null,
    },
    {
      id: 'prepare',
      title: 'Przygotowanie propozycji',
      kind: 'model',
      state: 'succeeded',
      dependsOn: ['read'],
      startedMs: 1,
      endedMs: 2,
      summary: 'Dane wpisane ręcznie. Nie wywołano modelu AI.',
      changesExternalState: false,
      approvalStepId: null,
      actorReference: null,
    },
    {
      id: 'approve',
      title: 'Akceptacja wersji',
      kind: 'approval',
      state: 'succeeded',
      dependsOn: ['prepare'],
      startedMs: 2,
      endedMs: 3,
      summary: 'Fixture stanu akceptacji, bez autoryzowania rzeczywistej operacji.',
      changesExternalState: false,
      approvalStepId: null,
      actorReference: 'fixture-reviewer',
    },
    {
      id: 'write',
      title: 'Wynik adaptera testowego',
      kind: 'tool',
      state: 'succeeded',
      dependsOn: ['prepare', 'approve'],
      startedMs: 3,
      endedMs: 4,
      summary: 'Testowy opis operacji. Żaden zewnętrzny rekord nie został zapisany.',
      changesExternalState: true,
      approvalStepId: 'approve',
      actorReference: null,
    },
    {
      id: 'verify',
      title: 'Sprawdzenie rezultatu',
      kind: 'verification',
      state: 'succeeded',
      dependsOn: ['write'],
      startedMs: 4,
      endedMs: 5,
      summary: 'Fixture weryfikacji, bez wyniku rzeczywistego narzędzia.',
      changesExternalState: false,
      approvalStepId: null,
      actorReference: null,
    },
  ],
};
