export { plContent } from './landing.pl';
export type {
  ContactContent,
  DemoPromise,
  DemoSprintStep,
  FaqItem,
  HeroContent,
  LandingContent,
  NavigationItem,
  PlaceholderCaseStudy,
  ProcessStep,
  ProductizedOffer,
  ProductShowcase,
  ProductVisualKind,
  SelectOption,
  SeoMetadata,
  ServiceOffering,
  StartingPackage,
  TechnologyCapability,
  TrustContent,
} from './landing-content.types';
